### ISSUE TITLE
ch4 : create_data.sh bug fix

### ISSUE THREAD

**Issue by karaopea** [PacktPublishing/Generative-Adversarial-Networks-Cookbook#5]
**1. DCGAN/docker/Dockerfile : ImportError: No module named 'cv2'**
- RUN pip3 install opencv-python <--- add

**2. DCGAN/scripts/create_data.sh : not found zip file**
- Download the data into our data folder
docker run -it \
        --runtime=nvidia \
        --rm \
        -v $HOME/DCGAN/data:/data \
        ch4 /bin/bash -c "unzip /data/church_outdoor_train_lmdb.zip -d /data/; unzip /data/church_outdoor_val_lmdb.zip -d /data/ ; mkdir /data/church_outdoor_train_lmdb/expanded"

**3. (docker)lsun/data.py : export lmdb to jpg has error fix**
- sudo docker run -it --rm ch4
- fix lsun/data.py
LINE 42 : image_out_dir = join(out_dir, '/'.join(key[:6].decode()))
LINE 47 : image_out_path = join(image_out_dir, key.decode() + '.webp')
LINE 50 : with open(image_out_path, 'wb') as fp:
- sudo docker commit [container] ch4:latest

**Comment by gaurav-packt** [comment]
Thanks for the resolution
